# Generated by Django 5.0.6 on 2024-06-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickynote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stickynote',
            name='title',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='stickynote',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
