# Generated by Django 5.0.6 on 2024-06-02 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0002_alter_stickynote_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stickynote',
            name='user',
        ),
    ]
