# Generated by Django 5.0.6 on 2024-06-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0003_remove_stickynote_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='stickynote',
            name='title',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
